blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('all-posts/',post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('<int:post_id>/comment/', post_comment, name='post_comment'),
    path('feed/',LatestPostsFeed(), name='post_feed'),
    path('search/',post_search, name='post_search'),
    path('contact/send-message/',send_message, name='sent_message'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts':PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Count

from taggit.managers import TaggableManager

# custom manager to retrieve all posts that have a PUBLISHED status.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, null=True, blank=True, unique_for_date='publish')
    image = models.ImageField(null=True,blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank = True, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager() # default manager
    published = PublishedManager() # custom manager issue

    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f'comment by {self.name} on {self.post.title} hello'

blog/forms.py
from django import forms
from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email  = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','body']

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import Http404
from blog.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView
from blog.forms import *
from django.core.mail import send_mail

from django.views.decorators.http import require_POST
from taggit.models import Tag

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

def home(request):
    recent_posts =  Post.published.order_by('-publish')[:3]
    all_tags = Tag.objects.all()
    return render(request, 'blog/home.html', {'recent_posts':recent_posts,'all_tags':all_tags})

def about(request):
    return render(request, 'blog/about.html')

def contact(request):
    return render(request, 'blog/contact.html')

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    all_tags = Tag.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 4)
    page_number = request.GET.get('page',1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        # assigning last page is out of range
        posts = paginator.page(paginator.num_pages)

    return render(request,'blog/post_list.html', {'posts':posts, 'all_tags':all_tags, 'tag':tag})


def post_detail(request,post, year, month, day):
    post = get_object_or_404(Post, slug=post,  publish__year=year,publish__month=month,publish__day=day, status=Post.Status.PUBLISHED)
    all_tags = Tag.objects.all()
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request, 'blog/post_detail.html', {'post':post, 'all_tags':all_tags,'comments':comments,'form':form, 'similar_posts': similar_posts})



def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data  = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{data['name']} recommends you to read {post.title}"
            message = f"Read {post.title} at {post_url} \n\n"
            send_mail(subject, message, 'hunterdbk5@gmail.com',[data['to']],fail_silently=False)
            sent = True

     
    else:
        form = EmailPostForm()
    return render(request, 'blog/share.html', {'post':post,'form':form,'sent':sent})

def send_message(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        print("=-----",name)
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        subject = f"{subject}"
        message = f"{message} \n\n"
        send_mail(subject, message, email,['hunterdbk5@gmail.com',],fail_silently=False)
        print("Email sent successfully -----------")
    return redirect(reverse('blog:contact'))



@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return redirect(post.get_absolute_url())
    return render(request, 'blog/comment.html',{'post':post, 'form':form, 'comment':comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body',weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector, rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
    return render(request, 'blog/search.html', {'form':form,'query':query, 'results':results})
            

blog/templates/blog/comment_form.html
<div class="col-lg-12">
    <div class="sidebar-item submit-comment">
        <div class="sidebar-heading">
            <h2>Your comment</h2>
        </div>
        <div class="content">
            <form id="comment" action="{% url 'blog:post_comment' post.id %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <fieldset>
                            <input name="name" type="text" id="name" placeholder="Your name" required="">
                        </fieldset>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <fieldset>
                            <input name="email" type="email" id="email" placeholder="Your email" required="">
                        </fieldset>
                    </div>
                    <div class="col-lg-12">
                        <fieldset>
                            <textarea name="body" rows="6" id="message" placeholder="Type your comment"
                                required=""></textarea>
                        </fieldset>
                    </div>
                    <div class="col-lg-12">
                        <fieldset>
                            <button type="submit" id="form-submit" class="main-button">Submit</button>
                        </fieldset>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

blog/templates/blog/home.html
{% extends "base.html" %}
{% load blog_tags %}
{% load humanize %}
{% load social_share %}

{% block title %}Home{% endblock %}

{% block content %}

<!-- Page Content -->

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text">
        <div class="container-fluid">
            <div class="owl-banner owl-carousel">
                
            </div>
        </div>
    </div>
    <!-- Banner Ends Here -->


<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        {% for post in recent_posts %}
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="{{ post.image.url }}" alt="{{ post.title }}">
                                </div>
                                <div class="down-content">
                                    <a href="{{ post.get_absolute_url }}">
                                        <h4>{{ post.title }}</h4>
                                    </a>
                                    <ul class="post-info">
                                        <li><a href="#">{{ post.author|capfirst }}</a></li>
                                        <li><a href="#">{{ post.publish|naturalday }}</a></li>
                                        <li><a href="#">{{ post.comments.count }} comment{{ post.comments.count|pluralize }}</a></li>

                                    </ul>
                                    <p>{{ post.body|truncatewords_html:30 }}</p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    {% for tag in post.tags.all %}
                                                    <li>
                                                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                                            {{ tag.name }}
                                                        </a>
                                                    </li>
                                                    {% if not forloop.last %}, {% endif %}
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                            <div class="col-6">
                                                <ul class="post-share">
                                                    <li><i class="fa fa-share-alt"></i></li>
                                                    <li>{% post_to_facebook object_or_url "Facebook" %}</li>
                                                    <li>{% post_to_twitter 'Share this' object_or_url "Twitter" %}</li>
                                                            
                                                        
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                        <div class="col-lg-12">
                            <div class="main-button">
                                <a href="{% url 'blog:post_list' %}">View All Posts</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2>Most Read Posts</h2>
                                </div>
                                <div class="content">
                                    {% get_most_commented_posts as most_commented_posts %}
                                    <ul>
                                            {% for post in most_commented_posts %}
                                                <li><a href="{{ post.get_absolute_url }}">
                                                        <h5>{{ post.title }}</h5>
                                                        <span>{{ post.publish|naturaltime }}</span>
                                                    </a></li>
                                            {% endfor %}
                                    </ul>
                                    
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="sidebar-item tags">
                                <div class="sidebar-heading">
                                    <h2>Tag Clouds</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        {% for tag in all_tags %}
                                        <li>
                                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                                {{ tag.name|title }}
                                            </a>
                                        </li>
                                        
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load blog_tags %}
{% load humanize %}
{% load social_share %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<!-- Page Content -->
<!-- Banner Starts Here -->
<div class="heading-page header-text">
    <section class="page-heading">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-content">
                        <h4>Post Details</h4>
                        <h2>Single blog post</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Banner Ends Here -->

<section class="blog-posts grid-system">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="{{ post.image.url }}" alt="{{ post.title }}">
                                </div>
                                <div class="down-content">
                                    <a href="{{ request.build_absolute_uri }}">
                                        <h4>{{ post.title }}</h4>
                                    </a>
                                    <ul class="post-info">
                                        <li><a href="#">{{ post.author|capfirst }}</a></li>
                                        <li><a href="#">{{ post.publish|naturalday }}</a></li>
                                        <li><a href="#">{{ post.comments.count }} comment{{ post.comments.count|pluralize }}</a></li>
                                    </ul>
                                    <p>{{ post.body }}</p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    {% for tag in post.tags.all %}
                                                        <li>
                                                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                                            {{ tag.name }}
                                                        </a>
                                                        </li>
                                                        {% if not forloop.last %}, {% endif %}
                                                    {% endfor %}

                                                </ul>
                                            </div>
                                            <div class="col-6">
                                                <ul class="post-share">
                                                    <li><i class="fa fa-share-alt"></i></li>
                                                    <li>{% post_to_facebook object_or_url "<p>Facebook</p>" %}</li>
                                                    <li>{% post_to_linkedin object_or_url %},</li>
                                                    <li>{% post_to_twitter 'Share this' object_or_url "<p>Twitter</p>" %}</li>
                                                    <li><a href="{% url 'blog:post_share' post.id %}">
                                                            Gmail
                                                    </a>,</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item comments">
                                <div class="sidebar-heading">
                                    {% with total_comments=comments.count %}
                                    <h2>
                                        {{ total_comments }} comment{{ total_comments|pluralize}}
                                    </h2>
                                    {% endwith %}
                                </div>
                                <div class="content">
                                    <ul>
                                        {% for comment in comments %}
                                            <li>
                                                <div class="author-thumb">
                                                    <img src="assets/images/comment-author-01.jpg" alt="">
                                                </div>
                                                <div class="right-content">
                                                    <h4>{{ comment.name}} <span> {{ comment.created }}</span></h4>
                                                    <p>{{ comment.body|linebreaks }}</p>
                                                </div>
                                            </li>
                                        {% empty %}
                                        <p>There are no comments.</p>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>

                    {% include 'blog/comment_form.html' %}
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form id="search_form" name="gs" method="GET" action="#">
                                    <input type="text" name="q" class="searchText" placeholder="type to search..."
                                        autocomplete="on">
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2>Recommended Posts</h2>
                                </div>
                                <div class="content">
              
                                    <ul>
                                        {% for post in similar_posts %}
                                            <li>
                                                <a href="{{ post.get_absolute_url }}">
                                                    <h5>{{ post.title }}</h5>
                                                    <span>{{ post.publish|naturalday }}</span>
                                                </a>
                                            </li>
                                        {% empty %}
                                        <p>There are no similar posts yet.</p>
                                        {% endfor %}

                                    </ul>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-lg-12">
                            <div class="sidebar-item tags">
                                <div class="sidebar-heading">
                                    <h2>Tag Clouds</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        {% for tag in all_tags %}
                                        <li>
                                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                                {{ tag.name|title }}
                                            </a>
                                        </li>
                                        
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/search.html
{% extends "base.html" %}
{% load blog_tags %}
{% load humanize %}

{% block title %}Search{% endblock %}
{% block content %}

<div class="main-banner header-text">
    <div class="container-fluid">
        <div class="owl-banner owl-carousel">
        </div>
    </div>
</div>

<section class="blog-posts grid-system ">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                {% if query %}
                <h3>Posts containing "{{ query }}":</h3>
                <h5>
                    {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}.
                    {% endwith %}
                </h5>
            </div>
        </div>


            <div class="row mt-3">
                {% for post in results %}
                <div class="col-lg-4">
                    <div class="blog-post">
                        <div class="blog-thumb">
                            <img src="{{ post.image.url }}" alt="{{post.title}}">
                        </div>
                        <div class="down-content">
                            <a href="{{ post.get_absolute_url }}">
                                <h4>{{ post.title|truncatewords_html:8 }}</h4>
                            </a>
                            <ul class="post-info">
                                <li><a href="#">{{post.author|capfirst }}</a></li>
                                <li><a href="#">{{ post.publish|naturalday }}</a></li>
                                <li><a href="#">{{ post.comments.count }} comment{{post.comments.count|pluralize }}</a></li>
                                        
                            </ul>
                            <p>{{ post.body|htmlformat|truncatewords_html:30 }}</p>
                            <div class="post-options">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <ul class="post-tags">
                                            <li><i class="fa fa-tags"></i></li>
                                            {% for tag in post.tags.all %}
                                            <li>
                                                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                                    {{ tag.name }}
                                                </a>
                                            </li>
                                            {% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>There are no results for your query.</p>
                <p><a href="{% url 'blog:home' %}">Search again</a></p>
                {% endfor %}
                
                {% else %}
                <h1>Search for posts</h1>
                <div class="col-lg-4">
                    <div class="sidebar">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="sidebar-item search">
                                    <form id="search_form" name="gs" method="get">
                                        <input type="text" name="query" class="searchText" placeholder="type to search..."
                                            autocomplete="on">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/navbar.html
{% load  static %}

<!-- ***** Preloader Start ***** -->
<div id="preloader">
    <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<!-- ***** Preloader End ***** -->

<!-- Header -->
<header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blog:home' %}">
                <h2>DBK Blog<em>.</em></h2>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blog:home' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:post_list' %}">Our Blogs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:about' %}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:contact' %}">Contact Us</a>
                    </li>
                        <li class="nav-item">
                            <div class="sidebar-item search">
                                <form id="search_form" name="gs" method="get" action="{% url 'blog:post_search' %}">
                                    <input type="text" name="query" class="searchText" placeholder="Search posts here..." autocomplete="on">
                                </form>
                            </div>
                            </li>
                        </li>
                </ul>
            </div>
        </div>
    </nav>
</header>


{% block script_js %}

{% endblock %}